# Generated by Django 5.0 on 2024-02-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='end_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='start_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
